app/quiz/models.py
from ..extensions import db
import datetime
from sqlalchemy.orm import object_session

from ..auth.models import User, UserAssignedQuiz, QuizRelatedQuestion

class Quiz(db.Model):
    __tablename__ = "quizes"
    __table_args__ = {"schema":"rts-schema"}

    id = db.Column(db.Integer, nullable=False, primary_key=True)
    title = db.Column(db.String(128), nullable=False)
    code = db.Column(db.String(16), nullable=False)
    
    # questions = db.relationship('Question', order_by='Question.id', backref = 'quiz', lazy = 'dynamic')

    user_assigned_quizes = db.relationship('UserAssignedQuiz', order_by='UserAssignedQuiz.id', backref = 'quiz', lazy = 'dynamic')
    quiz_related_questions = db.relationship('QuizRelatedQuestion', order_by='QuizRelatedQuestion.id', backref = 'quiz', lazy = 'dynamic')

    def flush(self):
        for item in self.quiz_related_questions:
            item.status = "hold"

    def __repr__(self):
        return "<Quiz {0}>".format(self.title)

    def __init__(self, title, hint):
        self.title = title
        self.code = title.split(' ')[0][0] + title.split(' ')[1][0] + "-" + self.uid

class Question(db.Model):
    __tablename__ = "questions"
    __table_args__ = {"schema":"rts-schema"}

    id = db.Column(db.Integer, nullable=False, primary_key=True)
    title = db.Column(db.String(128), nullable=False)
    hint = db.Column(db.String(128), nullable=False)

    quiz_related_questions = db.relationship('QuizRelatedQuestion', order_by='QuizRelatedQuestion.id', backref = 'question', lazy = 'dynamic')

    answers = db.relationship('Answer', order_by='Answer.id', backref = 'question', lazy = 'dynamic')
    attaches = db.relationship('Attach', order_by='Attach.id', backref = 'question', lazy = 'dynamic')

    def get_answers(self):
        return self.answers

    def get_attaches(self):
        return self.attaches

    def __repr__(self):
        return "<Question {0}, related to quiz {1}>".format(self.id, self.quiz_id)

    def __init__(self, title, hint, type, correct):
        self.title = title
        self.hint = hint
        self.type = type
        self.selected = ""
        self.correct = correct
        self.status = "hold"

class Answer(db.Model):
    __tablename__ = "answers"
    __table_args__ = {"schema":"rts-schema"}

    id = db.Column(db.Integer, nullable=False, primary_key=True)
    title = db.Column(db.String(64), nullable=False)
    question_id = db.Column(db.Integer, db.ForeignKey('rts-schema.questions.id'))
    correct = db.Column(db.Boolean, nullable=False, default=False)
    selected = db.Column(db.Boolean, nullable=False, default=False)

    def __repr__(self):
        return "<Answer {0}, related to question {1}>".format(self.id, self.question_id)

    def __init__(self, title):
        self.title = title

class Attach(db.Model):
    __tablename__ = "attaches"
    __table_args__ = {"schema":"rts-schema"}

    id = db.Column(db.Integer, nullable=False, primary_key=True)
    src = db.Column(db.String(255), nullable=False)
    question_id = db.Column(db.Integer, db.ForeignKey('rts-schema.questions.id'))

    def __repr__(self):
        return "<Attach {0}, related to question {1}>".format(self.id, self.question_id)

    def __init__(self, src):
        self.src = src

class Result(db.Model):
    __tablename__ = "results"
    __table_args__ = {"schema":"rts-schema"}

    id = db.Column(db.Integer, nullable=False, primary_key=True)
    result_string = db.Column(db.String(255), nullable=True)
    user_assigned_quiz_id = db.Column(db.Integer, db.ForeignKey('rts-schema.user_assigned_quizes.id'))

    def set_result(self, id, result):
        self.user_assigned_quiz_id = id
        self.result_string = result
    
    def __init__(self, id, result):
        self.user_assigned_quiz_id = id
        self.result_string = result

    def __repr__(self):
        return "<Result {0}, related to user {1}>".format(self.id, self.user_assigned_quiz_id)

app/quiz/forms.py
from flask_wtf import FlaskForm as Form
from flask import flash
from wtforms import StringField, PasswordField, SubmitField, BooleanField, RadioField
from wtforms.validators import Required, EqualTo
from models import db, Quiz, Question, Answer

class QuizForm(Form):
    SECRET_KEY="quiz_form_secret_key"

    answers = RadioField('Label', choices=[('value', 'description'),('value_two', 'whatever')])
    submit = SubmitField("Answer")

    def __init__(self, *args, **kwargs):
        Form.__init__(self, *args, **kwargs)

app/quiz/__init__.py
from flask import Blueprint
from views import *

quiz_route = Blueprint('quiz', __name__, template_folder="templates")

app/quiz/views.py
from __future__ import print_function
import datetime
import time

from flask import render_template, flash, request, session, redirect, url_for
from __init__ import quiz_route
from ..quiz.models import Quiz, Question, Result, db
from ..auth.models import User, UserAssignedQuiz, QuizRelatedQuestion
from forms import QuizForm
from ..main.decorators import admin_required, login_required


@login_required
@quiz_route.route('/<quiz_id>/')
def quiz(quiz_id):
    quiz_form = QuizForm()

    user = User.query.filter_by(email=session['email']).first()
    assigned_quiz = user.get_assigned_quiz(quiz_id)
    
    if request.method == 'GET':
        if assigned_quiz.status == "completed":
                return redirect(url_for('quiz.completed', quiz_id=quiz_id))
        else:
            # Quiz starts
            assigned_quiz.start()
            related_questions = assigned_quiz.quiz.quiz_related_questions.paginate(page=assigned_quiz.quiz.quiz_related_questions.count(), per_page=1)
            current_question = related_questions.query.first()
            current_question.set_active()
            return render_template('quiz/quiz.html', form=quiz_form, assigned_quiz=assigned_quiz, user=user, current_question=current_question)
        #         return redirect(url_for('main.home'))
        

@login_required
@admin_required
@quiz_route.route('/<quiz_id>/edit/assign/', methods=['GET','POST'])
def assign_quiz(quiz_id):

    current_quiz = Quiz.query.filter_by(id=quiz_id).first()
    userid = request.form['quiz_edit_adduser_field']
    assigned_quiz = UserAssignedQuiz.query.filter_by(user_id=userid).first()

    user = User.query.filter_by(id=userid).first()

    if request.method == 'POST':
        if 'all' in request.form['quiz_edit_assign_all']:
            all_users = User.query.all()
            for user in all_users:
                new_assignation = UserAssignedQuiz(user.id, current_quiz.id, "hold", None, None, 0, 0)
                db.session.add(new_assignation)
                db.session.commit()
            flash(u'Successfully assigned quiz "{0}" to all users!'.format(current_quiz.title))
            return redirect(url_for('quiz.edit_quiz', quiz_id=current_quiz.id))
        else:
            if not assigned_quiz:
                new_assignation = UserAssignedQuiz(userid, current_quiz.id, "hold", None, None, 0, 0)
                db.session.add(new_assignation)
                db.session.commit()
                flash(u'Successfully assigned quiz "{0}" to user "{1}"!'.format(user.id, current_quiz.title))
                return redirect(url_for('quiz.edit_quiz', quiz_id=current_quiz.id))
            else:
                flash('Error: Already assigned!')
                return redirect(url_for('quiz.edit_quiz', quiz_id=current_quiz.id))
    else:
        flash('Error: Only POST method is allowed!')
        return redirect(url_for('quiz.edit_quiz', quiz_id=current_quiz.id))

@login_required
@admin_required
@quiz_route.route('/<quiz_id>/edit/deassign/<user_id>/', methods=['GET', 'POST'])
def deassign_quiz(quiz_id, user_id):

    current_quiz = Quiz.query.filter_by(id=quiz_id).first()
    assigned_quiz = UserAssignedQuiz.query.filter_by(user_id=user_id).first()

    user = User.query.filter_by(id=user_id).first()

    if request.method == 'POST':
        if assigned_quiz:
            db.session.delete(assigned_quiz)
            db.session.commit()
            flash(u'Successfully deassigned quiz "{0}" off user "{1}"'.format(current_quiz.title, user.name))
            return redirect(url_for('quiz.edit_quiz', quiz_id=current_quiz.id))
        else:
            flash('Error: No quiz dessigned!')
            return redirect(url_for('quiz.edit_quiz', quiz_id=current_quiz.id))
    else:
        flash('Error: Only POST method is allowed!')
        return redirect(url_for('quiz.edit_quiz', quiz_id=current_quiz.id))

@login_required
@quiz_route.route('/<quizid>/question/<question_id>/answer/', methods=['GET','POST'])
def answer_quiz(quizid, question_id):
    quiz_form = QuizForm()

    user = User.query.filter_by(email=session['email']).first()
    assigned_quiz = user.get_assigned_quiz(quizid)

    questions = assigned_quiz.quiz.quiz_related_questions.paginate(page=assigned_quiz.quiz.quiz_related_questions.count(), per_page=1)
    question = questions.query.first()

    result = Result.query.filter_by(user_assigned_quiz_id=assigned_quiz.user_id).first()

    if request.method == 'POST':
        if not question is None:
            if question.type == "single":
                user_answer = request.form['radio_answer']
            elif question.type == "multi":
                user_answer = request.form['checkbox_answer']
            
            question.answer(user_answer)

            # if result is None:
            #     new_result = Result(assigned_quiz.quiz_id, user_answer)
            #     db.session.add(new_result)
            #     db.session.commit()
            # else:
            #     result.set_result(assigned_quiz.quiz_id, user_answer)
            #     db.session.commit()

            if question:
                next_question = questions.next()
                assigned_quiz.quiz.flush()
                next_question.items.first().set_active()
            else:
                assigned_quiz.finish()
                return redirect(url_for('quiz.completed', quiz_id=assigned_quiz.quiz_id))
            db.session.commit()
            return render_template('quiz/quiz.html', form=quiz_form, assigned_quiz=assigned_quiz, current_question=next_question, user=user)
    elif request.method == 'GET':
        return redirect(url_for('quiz.quiz', quiz_id=assigned_quiz.quiz_id))

@login_required
@quiz_route.route('/<quiz_id>/completed/')
def completed(quiz_id):
    user = User.query.filter_by(email=session['email']).first()
    assigned_quiz = UserAssignedQuiz.query.filter_by(quiz_id=quiz_id).first()

    if assigned_quiz.status == "completed":
        return render_template('quiz/completed.html', user=user, assigned_quiz=assigned_quiz)
    else:
        return redirect(url_for('quiz.quiz', quiz_id=assigned_quiz.id))

@login_required
@quiz_route.route('/<quiz_id>/create-report-<report_type>')
def create_report(quiz_id, report_type):
    if(report_type in ["xml"]):
        report = make_xml_report()
    elif(report_type in ["excel", "xls"]):
        report = make_xls_report()
    elif(report_type in ["doc", "word"]):
        report = make_doc_report()
    else:
        flash('Error: This filetype of report is not supported!')
        return redirect(url_for('quiz.completed', quiz_id=quiz_id))
    


@login_required
@admin_required
@quiz_route.route('/<quiz_id>/edit/', methods=['GET', 'POST'])
def edit_quiz(quiz_id):

    current_quiz = Quiz.query.filter_by(id=quiz_id).first()
    users = User.query.order_by(User.id.asc()).all()

    assigned_users = UserAssignedQuiz.query.filter_by(quiz_id=quiz_id).all()

    if request.method == 'POST':
            # your action here
            db.session.commit()
            return redirect(url_for('main.home'))
    elif request.method == 'GET':
            # if quiz:
            #         return redirect(url_for('quiz.quiz'))
            # else:
            #         return redirect(url_for('main.home'))
            return render_template('quiz/edit.html', current_quiz=current_quiz, assigned_users=assigned_users, users=users)

@login_required
@admin_required
@quiz_route.route('/<quiz_id>/remove-quiz/')
def remove_quiz(quiz_id):
    
    quiz = Quiz.query.filter_by(id=quiz_id).first()

    if request.method == 'POST':
        db.session.delete(quiz)
        db.session.commit()
        flash(u'Successfully deassigned quiz "{0}" off user "{1}"'.format(current_quiz.title, user.name))
        return redirect(url_for('quiz.edit_quiz', quiz_id=current_quiz.id))

@login_required
@admin_required
@quiz_route.route('/<quizid>/remove-question/<questionid>/', methods=['GET', 'POST'])
def remove_question(quizid, questionid):
    
    related_question = QuizRelatedQuestion.query.filter_by(quiz_id=quizid).filter_by(question_id=questionid).first()

    if request.method == 'POST':
        if related_question:
            # Achtung! Removing by CASCADE!
            db.session.delete(related_question.question)
            db.session.delete(related_question)
            db.session.commit()
            flash(u'Successfully removed question "{0}" from quiz "{1}"'.format(related_question.question_id, current_quiz.title))
            return redirect(url_for('quiz.edit_quiz', quiz_id=current_quiz.id))
    elif request.method == 'GET':
        flash('Only POST method is allowed!')
        return redirect(url_for('admin.home'))


@login_required
@admin_required
@quiz_route.route('/<quiz_id>/completed/details/')
def quiz_detail(quiz_id):
    quiz = Quiz.query.order_by(Quiz.id.asc()).filter_by(id=quiz_id).first()
    users = User.query.order_by(User.id.asc()).all()

    if request.method == 'POST':
            # your action here
            db.session.commit()
            return redirect(url_for('main.home'))
    elif request.method == 'GET':
            # if quiz:
            #         return redirect(url_for('quiz.quiz'))
            # else:
            #         return redirect(url_for('main.home'))
            return render_template('quiz/detail.html', quiz=quiz, users=users)

app/templates/quiz/completed.html
<!DOCTYPE html> {% extends "template.html" %} {% block quiz_completed_content %}
<div class="panel panel-info">
    <div class="panel-heading text-center">
        <h1>Тест завершён</h1>
    </div>
    <div class="panel-body">
        <div class="row text-center">
            <div class="col-xs-6 pull-left">
                <h2 class="text-info">Тест:</h2>
                <h3>{{ assigned_quiz.quiz.title }}</h3>
            </div>
            <div class="col-xs-6 pull-right">
                <h2 class="text-info">Пользователь:</h2>
                <h3>{{ user.name }}</h3>
            </div>
        </div>
        <hr>
        <table class="table">
            <caption class="text-center">
                <h3>Статистика прохождения (<a href="{{ url_for('quiz.quiz_detail', quiz_id=assigned_quiz.id) }}">подробности</a>)</h3>
            </caption>
            <thead>
                <tr>
                    <th>Вопрос</th>
                    <th class="text-center">Выбранный ответ</th>
                    <th class="text-center">Ответил правильно</th>
                </tr>
            </thead>
            <tbody>
                {% for question in assigned_quiz.quiz.get_questions() %}
                <tr>
                    <td><strong>{{ loop.index }}.</strong>&nbsp;{{ question.title }}</td>
                    <td class="text-center">
                    {% for answer in question.get_answers() %}
                        {% if answer.selected == True and answer.question_id == question.id %}
                        <em>"{{ answer.title }}"</em>
                        {% endif %}
                    {% endfor %}
                    </td>
                    {% if question.check_correct() == 'True' %}
                    <td class="text-center text-success"><strong>да</strong></td>
                    {% else %}
                    <td class="text-center text-danger"><strong>нет</strong></td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>
<div>
    <div class="row">
        <div class="col-xs-12">
            <h2 class="text-center">Общий балл:</h2>
            {% if score == 3: %}
                <h2 class="text-center text-warning"><strong>{{ assigned_quiz.score }}</strong> ({{ assigned_quiz.percentage }}%)</h2>
            {% elif score == 2: %}
                <h2 class="text-center text-danger"><strong>{{ assigned_quiz.score }}</strong> ({{ assigned_quiz.percentage }}%)</h2>
            {% else %}
                <h2 class="text-center text-success"><strong>{{ assigned_quiz.score }}</strong> ({{ assigned_quiz.percentage }}%)</h2>
            {% endif %}
        </div>
    </div>
</div>
<hr>
<div class="">
    {% if user.role == "admin" %}
    <div class="row">
        <div class="col-xs-12">
            <h4 class="text-center">
                <i class="glyphicon glyphicon-save"></i>&nbsp;Сохранить отчёт
            </h4>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-xs-12 text-center">
            <div class="btn-group " role="group" aria-label="...">
                <button type="button" class="btn btn-success">XML</button>
                <button disabled type="button " class="btn btn-info">Excel</button>
                <button disabled type="button disabled" class="btn btn-danger">Word</button>
            </div>
        </div>
    </div>
    <hr>
    {% endif %}
    <div class="row">
        <div class="col-xs-12 text-center">
            <a class="btn btn-default" href="{{ url_for('main.home') }}">Закрыть страницу</a>
        </div>
    </div>
    <br>


</div>
{% endblock %}

app/templates/quiz/detail.html
<!DOCTYPE html> {% extends "template.html" %} {% block quiz_detail_content %}
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="row">
                <div class="col-xs-12 text-center">
                    <h3><a href="{{ url_for('quiz.completed', quiz_id=quiz.id) }}">Вернуться к общей статистике</a></h3>
                </div>
            </div>
            <br>
            {% for question in quiz.get_questions() %}
            <div class="row">
                <div class="col-xs-12">
                    <div class="panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title">Вопрос {{ question.id }}</h3>
                        </div>
                        <div class="panel-body">
                            <p class="lead">{{ question.title }}</p>
                        </div>
                        {%if question.hint != "" %}
                        <div class="panel-footer text-muted">
                            <small><strong>Подсказка:</strong> {{ question.hint }}</small>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>

            <br> {% for attach in question.get_attaches() %}
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <img class="img-responsive center-block img-rounded" id="img_attach_to_question_{{ question.id }}" src="{{ attach.src }}"
                            alt="">
                    </div>
                </div>
            </div>
            {% endfor %}

            <br>
            <div class="row">
                <div class="col-xs-12">
                    <div class="panel panel-default panel-body">
                        {% for answer in question.get_answers() %} 
                        {% if answer.correct and answer.selected %}
                        <div class="checkbox">
                            <label class="large">
                                <span class="text-success glyphicon glyphicon-ok"></span>&nbsp;{{ answer.title }}
                            </label>
                        </div>
                        {% elif not answer.correct and answer.selected %}
                        <div class="checkbox">
                            <label>
                                <span class="text-danger glyphicon glyphicon-remove"></span>&nbsp;{{ answer.title }}
                            </label>
                        </div>

                        {% else %}
                        <div class="checkbox">
                            <label>
                                <span class="glyphicon glyphicon-record"></span>&nbsp;{{ answer.title }}
                            </label>
                        </div>

                        {% endif %} {% endfor %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

app/templates/quiz/list.html
<!DOCTYPE html>
{% extends "template.html" %}
{% block quiz_list_content %}
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h3 class="text-center">Тесты, назначенные пользователю {{ user.name }}:</h3>
            <br>
            <ul class="list-group">
                {% for assigned_quiz in assigned_quizes %}
                    <li class="list-group-item">
                        <div class="pull-right">
                            {% if assigned_quiz.status == "completed" %}
                            <span class="label label-success">Завершён</span>
                            {% elif assigned_quiz.status == "active" %}
                            <span class="label label-info">В процессе</span>
                            {% else %}
                            <span class="label label-default">Не начат</span>
                            {% endif %}
                        </div>
                        <strong>{{ loop.index }}.&nbsp;</strong><a href="{{ url_for('quiz.quiz', quiz_id=assigned_quiz.quiz_id) }}">{{ assigned_quiz.quiz.title }}</a>
                        {% if assigned_quiz.percentage > 0 %}
                        <span class="label label-info">{{ assigned_quiz.percentage }}%</span>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-xs-12">
            <h3 class="text-center">Список тестов:</h3>
            <br>
            <ul class="list-group">
                {% for quiz in all_quizes %}
                {% set loop_index = loop.index %}
                    <li class="list-group-item">
                        <strong>{{ loop_index }}.&nbsp;</strong>{{ quiz.title }}
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

app/templates/quiz/quiz.html
<!DOCTYPE html> {% extends "template.html" %} {% block quiz_content %}
<div class="container">
    <div class="row">
        <div class="col-xs-6 pull-left">
            <h2 class="text-success">Тест {{ assigned_quiz.quiz_id }}.</h2>
            <h3>{{ assigned_quiz.quiz.title }}</h3>
        </div>
        <div class="col-xs-6 pull-right">
            <h2 class="text-success">Пользователь:</h2>
            <h3>{{ user.name }}</h3>
        </div>
    </div>

    <br>
    <div class="row">
        <div class="col-xs-12">
            <div class="center-block">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% for question_entry in assigned_quiz.quiz.quiz_related_questions %}
                            {% set loop_index = loop.index %}
                            {% if question_entry.status == "active" %}
                            <li class="active"><a>{{ loop_index }}</a></li>
                            {% else %}
                            <li><a>{{ loop_index }}</a></li>
                            {% endif %} 
                        {% endfor %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    {% if current_question.status == "active" %}
    <div class="row">
        <div class="col-xs-12">
            <div class="panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">Вопрос</h3>
                </div>
                <div class="panel-body">
                    <p class="lead">{{ current_question.question.title }}</p>
                </div>
                {%if current_question.question.hint != "" %}
                <div class="panel-footer text-muted">
                    <button type="button" class="close" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <small>
                        <strong>Подсказка:</strong> {{ current_question.question.hint }}</small>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

    <br> {% for attach in current_question.question.get_attaches() %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <img class="img-responsive center-block img-rounded" id="img_attach_to_question_{{ current_question.question.id }}" src="{{ attach.src }}"
                    alt="">
            </div>
        </div>
    </div>
    {% endfor %}
    <br>
    <form method="POST" action="{{ url_for('quiz.answer_quiz', quizid=assigned_quiz.quiz_id, question_id=current_question.question.id) }}">
        <div class="row">
            <div class="col-xs-12">
                <div class="panel panel-default panel-body">
                    {% for answer in current_question.question.answers %} 
                    {% if current_question.type == "single" %}
                    <div class="radio">
                        <label class="large">
                            {% if answer == current_question.question.answers[0] %}
                            <input checked type="radio" name="radio_answer" id="radio_answer_chk" value="{{ answer.title }}"> {{ answer.title }}
                            {% else: %}
                            <input type="radio" name="radio_answer" id="radio_answer_nchk" value="{{ answer.title }}"> {{ answer.title }}
                            {% endif %}
                        </label>
                    </div>
                    {% elif current_question.type == "multi" %}
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="checkbox_answer" id="checkbox_answer"> {{ answer.title }}
                        </label>
                    </div>
                    {% endif %} 
                    {% endfor %}
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-xs-12">
                <div class="text-center">
                    {{ form.submit(class_="answer-button btn btn-success") }}
                </div>
            </div>
        </div>
    </form>
    {% endif %}
    <br>
</div>
{% endblock %}